name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every 2 hours
    - cron: "0 */2 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
      - name: Set global directory
        run: git config --global --add safe.directory /github/workspace
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
      - name: Commit changes
        run: |
          git config --local user.email "wwicaksono96@gmail.com"
          git config --local user.name "wiscaksono"
          git add -A
          arr[0]="feat: 🎉 reforestation"
          arr[1]="feat: 🌳 reforestation"
          arr[2]="feat: ✅ reforestation"
          arr[3]="feat: 🌲 reforestation"
          rand=$[$RANDOM % ${#arr[@]}]
          git commit -m "${arr[$rand]}"
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
